name: Build
on:
  push:
    branches:
     - "*"
    tags:
     - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.21.x
      - uses: actions/checkout@v2
      - name: install deps
        run: make install
      - name: build
        run: make build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: bin/*
      - name: Release
        if: contains(github.ref, 'tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
  
  create-release:
    runs-on: ubuntu-latest
