name: Build
on:
  push:
    branches:
     - "**"
    tags:
     - "v*"
     - "n*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.21.x
      - uses: actions/checkout@v2
      - name: echo version
        run: echo -e "export const VERSION = \"${GITHUB_REF#refs/*/}\";\n" > src/version.ts
      - name: cache deps
        run: deno task cache
      - name: build
        run: deno task build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dlsl_preproc.exe
          path: bin/dlsl_preproc.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dlsl_preproc
          path: bin/dlsl_preproc
      - name: Release
        if: contains(github.ref, 'tags/v')
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/*
          token: ${{ secrets.GITHUB_TOKEN }}
