name: Build
on:
  push:
    branches:
     - "*"
    tags:
     - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.21.x
      - uses: actions/checkout@v2
      - name: install deps
        run: make install
      - name: build
        run: make build
